on:
  push:                                                                                        
    branches: [ master ]
  pull_request:                                                                                
    branches: [ master ]         

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
    - run: ruby generate.rb
    - run: mv .gitignore.build .gitignore
    - uses: JamesIves/github-pages-deploy-action@v4
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      with:
        git-config-name: 'RubyElders bot'
        git-config-email: 'info@rubyelders.com'
        branch: gh-pages # The branch the action should deploy to.
        folder: . # The folder the action should deploy.
        clean: true # Automatically remove deleted files from the deploy branch
